<template>
  <Head title="Privacy Policy | Room Rise" />

  <section class="page">
    <div class="hero">
      <div class="hero-inner">
        <h1 class="title">Privacy Policy</h1>
        <p class="subtitle">Privacy Policy for <strong>Roomrise</strong></p>
      </div>
    </div>

    <div class="content-wrap">
      <aside class="toc" aria-label="Table of contents">
        <div class="toc-card">
          <div class="toc-head">On this page</div>
          <nav>
            <ol>
              <li><a href="#intro">Introduction</a></li>
              <li>
                <a href="#definitions">Interpretation & Definitions</a>
                <ol>
                  <li><a href="#interpretation">Interpretation</a></li>
                  <li><a href="#defs">Definitions</a></li>
                </ol>
              </li>
              <li>
                <a href="#collecting">Collecting & Using Data</a>
                <ol>
                  <li><a href="#personal-data">Personal Data</a></li>
                  <li><a href="#usage-data">Usage Data</a></li>
                  <li><a href="#use-of-data">Use of Your Data</a></li>
                </ol>
              </li>
              <li><a href="#retention">Retention</a></li>
              <li><a href="#transfer">Transfer</a></li>
              <li><a href="#delete">Delete Your Data</a></li>
              <li><a href="#disclosure">Disclosure</a></li>
              <li><a href="#security">Security</a></li>
              <li><a href="#children">Children's Privacy</a></li>
              <li><a href="#links">Links to Other Websites</a></li>
              <li><a href="#changes">Changes to this Policy</a></li>
            </ol>
          </nav>
        </div>
      </aside>
      <article class="prose card">
        <section id="intro">
          <p>
            This Privacy Policy describes our policies and procedures on the
            collection, use and disclosure of your information when you use the
            Service and tells you about your privacy rights and how the law
            protects you. We use your personal data to provide and improve the
            Service. By using the Service, you agree to the collection and use
            of information in accordance with this Privacy Policy.
          </p>
        </section>

        <section id="definitions">
          <h2>Interpretation and Definitions</h2>

          <h3 id="interpretation">Interpretation</h3>
          <p>
            The words of which the initial letter is capitalized have meanings
            defined under the following conditions. The following definitions
            shall have the same meaning regardless of whether they appear in
            singular or in plural.
          </p>

          <h3 id="defs">Definitions</h3>
          <p>For the purposes of this Privacy Policy:</p>
          <ul>
            <li>
              <strong>Account</strong> means a unique account created for you to
              access our Service or parts of our Service.
            </li>
            <li>
              <strong>Affiliate</strong> means an entity that controls, is
              controlled by or is under common control with a party, where
              "control" means ownership of 50% or more of the shares, equity
              interest or other securities entitled to vote for election of
              directors or other managing authority.
            </li>
            <li>
              <strong>Application</strong> refers to Roomrise, the software
              program provided by the Company.
            </li>
            <li>
              <strong>Company</strong> (referred to as either "the Company",
              "we", "us" or "our" in this Agreement) refers to Roomrise.
            </li>
            <li><strong>Country</strong> refers to: Vietnam.</li>
            <li>
              <strong>Device</strong> means any device that can access the
              Service such as a computer, a cellphone or a digital tablet.
            </li>
            <li>
              <strong>Personal Data</strong> is any information that relates to
              an identified or identifiable individual.
            </li>
            <li><strong>Service</strong> refers to the Application.</li>
            <li>
              <strong>Service Provider</strong> means any natural or legal
              person who processes the data on behalf of the Company.
            </li>
            <li>
              <strong>Usage Data</strong> refers to data collected
              automatically, either generated by the use of the Service or from
              the Service infrastructure itself.
            </li>
            <li>
              <strong>You</strong> means the individual accessing or using the
              Service, or the company or other legal entity on behalf of which
              such individual is accessing or using the Service, as applicable.
            </li>
          </ul>
        </section>

        <section id="collecting">
          <h2>Collecting and Using Your Personal Data</h2>
          <h3>Types of Data Collected</h3>

          <h4 id="personal-data">Personal Data</h4>
          <p>
            While using our Service, we may ask you to provide us with certain
            personally identifiable information, including:
          </p>
          <ul>
            <li>Email address</li>
            <li>First name and last name</li>
            <li>Phone number</li>
            <li>Address, State, Province, ZIP/Postal code, City</li>
            <li>Usage Data</li>
          </ul>

          <h4 id="usage-data">Usage Data</h4>
          <p>
            Usage Data is collected automatically when using the Service and may
            include information such as your device's IP address, browser type
            and version, pages visited, timestamps, time spent, device
            identifiers and other diagnostic data. When you access the Service
            by or through a mobile device, we may collect additional information
            such as device type, unique ID, IP address, operating system, mobile
            browser type, device identifiers and other diagnostic data.
          </p>

          <h3 id="use-of-data">Use of Your Personal Data</h3>
          <p>The Company may use Personal Data for the following purposes:</p>
          <ul>
            <li>
              To provide and maintain our Service, including to monitor the
              usage of our Service.
            </li>
            <li>
              To manage your Account and registration as a user of the Service.
            </li>
            <li>For the performance of a contract with you.</li>
            <li>
              To contact you via email, telephone, SMS, or other equivalent
              forms of electronic communication.
            </li>
            <li>
              To provide you with news, special offers and general information
              about goods, services and events similar to those you have
              purchased or enquired about unless you have opted out.
            </li>
            <li>To attend and manage your requests to us.</li>
            <li>
              For business transfers, including evaluating or conducting
              mergers, reorganizations, or similar transactions.
            </li>
            <li>
              For other purposes such as data analysis, identifying usage
              trends, measuring campaign effectiveness and improving our Service
              and experience.
            </li>
          </ul>

          <p>
            We may share your personal information in the following situations:
            with service providers; for business transfers; with affiliates;
            with business partners; with other users when information is shared
            publicly; and with your consent.
          </p>
        </section>

        <section id="retention">
          <h2>Retention of Your Personal Data</h2>
          <p>
            The Company will retain your Personal Data only for as long as is
            necessary for the purposes set out in this Privacy Policy, and as
            needed to comply with legal obligations, resolve disputes, and
            enforce agreements. Usage Data is generally retained for a shorter
            period unless needed to improve security or functionality or when
            legally obligated for longer.
          </p>
        </section>

        <section id="transfer">
          <h2>Transfer of Your Personal Data</h2>
          <p>
            Your information may be transferred to and maintained on computers
            located outside your jurisdiction, where data protection laws may
            differ. We will take all steps reasonably necessary to ensure your
            data is treated securely and in accordance with this Privacy Policy,
            and no transfer will take place without adequate controls in place.
          </p>
        </section>

        <section id="delete">
          <h2>Delete Your Personal Data</h2>
          <p>
            You have the right to delete or request that we assist in deleting
            the Personal Data that we have collected about you. Depending on the
            Service, you may be able to delete certain information from within
            the Service or update, amend, or delete information via your Account
            settings. You may also contact us to request access to, correct, or
            delete personal information you have provided.
          </p>
        </section>

        <section id="disclosure">
          <h2>Disclosure of Your Personal Data</h2>

          <h4>Business Transactions</h4>
          <p>
            If the Company is involved in a merger, acquisition, or asset sale,
            your Personal Data may be transferred, with notice provided before
            your Personal Data becomes subject to a different Privacy Policy.
          </p>

          <h4>Law Enforcement</h4>
          <p>
            Under certain circumstances, the Company may be required to disclose
            your Personal Data if required to do so by law or in response to
            valid requests by public authorities.
          </p>

          <h4>Other Legal Requirements</h4>
          <p>
            The Company may disclose your Personal Data in good faith belief
            that such action is necessary to comply with a legal obligation,
            protect and defend our rights or property, prevent wrongdoing,
            protect the personal safety of users or the public, or protect
            against legal liability.
          </p>
        </section>

        <section id="security">
          <h2>Security of Your Personal Data</h2>
          <p>
            While we strive to use commercially acceptable means to protect your
            Personal Data, no method of transmission over the Internet or
            electronic storage is 100% secure. We cannot guarantee absolute
            security.
          </p>
        </section>

        <section id="children">
          <h2>Children's Privacy</h2>
          <p>
            Our Service does not address anyone under the age of 13. We do not
            knowingly collect personally identifiable information from anyone
            under 13. If you are a parent or guardian and become aware that your
            child has provided us with Personal Data, please contact us so we
            can take steps to remove that information.
          </p>
        </section>

        <section id="links">
          <h2>Links to Other Websites</h2>
          <p>
            Our Service may contain links to other websites that are not
            operated by us. We strongly advise you to review the Privacy Policy
            of every site you visit. We have no control over and assume no
            responsibility for the content, privacy policies or practices of any
            third-party sites or services.
          </p>
        </section>

        <section id="changes">
          <h2>Changes to this Privacy Policy</h2>
          <p>
            We may update our Privacy Policy from time to time. We will notify
            you of any changes by posting the new Privacy Policy on this page
            and update the "Last updated" date above. You are advised to review
            this Privacy Policy periodically for any changes. Changes are
            effective when posted on this page.
          </p>
        </section>

        <footer class="doc-footer">© Roomrise</footer>
      </article>
    </div>
  </section>
</template>

<script setup>
import { Head } from "@inertiajs/vue3";
import { onBeforeUnmount, onMounted } from "vue";

onMounted(() => {
  const toc = document.querySelector(".toc");
  if (!toc) return;

  const items = Array.from(toc.querySelectorAll("nav li"));
  const links = Array.from(toc.querySelectorAll('a[href^="#"]'));
  if (!links.length) return;

  const liById = new Map();
  links.forEach((a) => {
    const id = decodeURIComponent(
      (a.getAttribute("href") || "").replace(/^#/, "")
    );
    const li = a.closest("li");
    if (id && li) liById.set(id, li);
  });

  const sections = Array.from(
    document.querySelectorAll(
      "article.prose section[id], article.prose h2[id], article.prose h3[id], article.prose h4[id]"
    )
  );

  let positions = [];
  const HEADER_OFFSET = 90;
  const VIEWPORT_ANCHOR = 0.35;
  const HYSTERESIS = 24;
  let lastActiveIndex = -1;

  const measure = () => {
    positions = sections
      .map((el) => ({
        id: el.id,
        top: el.getBoundingClientRect().top + window.scrollY,
      }))
      .sort((a, b) => a.top - b.top);
  };

  const activateByIndex = (idx) => {
    if (idx === lastActiveIndex || idx < 0 || idx >= positions.length) return;

    items.forEach((li) => li.classList.remove("active"));
    const id = positions[idx].id;
    const li = liById.get(id);
    if (li) li.classList.add("active");
    lastActiveIndex = idx;
  };

  const computeIndex = () => {
    const refLine =
      window.scrollY + window.innerHeight * VIEWPORT_ANCHOR - HEADER_OFFSET;

    let idx = -1;
    for (let i = 0; i < positions.length; i++) {
      if (positions[i].top <= refLine) idx = i;
      else break;
    }
    if (idx < 0) idx = 0;

    if (lastActiveIndex >= 0 && lastActiveIndex < positions.length) {
      const lastTop = positions[lastActiveIndex].top;
      const delta = Math.abs(refLine - lastTop);
      if (delta < HYSTERESIS) return lastActiveIndex;
    }
    return idx;
  };

  let ticking = false;
  const onScroll = () => {
    if (ticking) return;
    ticking = true;
    requestAnimationFrame(() => {
      const idx = computeIndex();
      activateByIndex(idx);
      ticking = false;
    });
  };

  const onResize = () => {
    measure();
    const idx = computeIndex();
    activateByIndex(idx);
  };

  measure();
  onScroll();

  window.addEventListener("scroll", onScroll, { passive: true });
  window.addEventListener("resize", onResize);

  const article = document.querySelector("article.prose");
  let ro;
  if (article && "ResizeObserver" in window) {
    ro = new ResizeObserver(() => onResize());
    ro.observe(article);
  }

  const onHash = () => {
    const id = decodeURIComponent(location.hash.replace(/^#/, ""));
    const idx = positions.findIndex((p) => p.id === id);
    if (idx !== -1) activateByIndex(idx);
  };
  window.addEventListener("hashchange", onHash);
  if (location.hash) onHash();

  window.__rr_cleanup__ = () => {
    window.removeEventListener("scroll", onScroll);
    window.removeEventListener("resize", onResize);
    window.removeEventListener("hashchange", onHash);
    if (ro) ro.disconnect();
  };
});

onBeforeUnmount(() => {
  const f = window.__rr_cleanup__;
  if (typeof f === "function") f();
});
</script>

<style scoped>
:root {
  --bg: #fff;
  --text: #0f172a;
  --muted: #64748b;
  --card: #fff;
  --ring: #e2e8f0;
  --accent: #2563eb;
  --accent-soft: rgba(37, 99, 235, 8%);
  --shadow: 0 6px 24px rgba(2, 6, 23, 6%);
}

@media (prefers-color-scheme: dark) {
  :root {
    --bg: #0b1224;
    --text: #e6edf7;
    --muted: #9aa7be;
    --card: #0f172a;
    --ring: #1f2a44;
    --accent: #60a5fa;
    --accent-soft: rgba(96, 165, 250, 12%);
    --shadow: 0 8px 30px rgba(0, 0, 0, 35%);
  }
}

.page {
  background: radial-gradient(
      900px 500px at 10% -10%,
      var(--accent-soft),
      transparent 60%
    ),
    radial-gradient(
      800px 400px at 110% 0%,
      rgba(16, 185, 129, 10%),
      transparent 55%
    ),
    var(--bg);
  min-block-size: 100dvh;
}

.hero {
  padding-block: 36px 12px;
  padding-inline: 16px;
}

.hero-inner {
  border: 1px solid var(--ring);
  border-radius: 18px;
  backdrop-filter: blur(6px);
  background: linear-gradient(
    180deg,
    rgba(255, 255, 255, 45%),
    rgba(255, 255, 255, 15%)
  );
  box-shadow: var(--shadow);
  margin-inline: auto;
  max-inline-size: 1100px;
  padding-block: 28px 18px;
  padding-inline: 28px;
}

@media (prefers-color-scheme: dark) {
  .hero-inner {
    background: linear-gradient(
      180deg,
      rgba(255, 255, 255, 5%),
      rgba(255, 255, 255, 3%)
    );
  }
}

@supports not (
  (backdrop-filter: blur(6px)) or (-webkit-backdrop-filter: blur(6px))
) {
  .hero-inner {
    background: var(--card);
  }
}

.title {
  color: var(--text);
  font-size: clamp(28px, 2.6vw, 36px);
  letter-spacing: 0.2px;
  line-height: 1.2;
  margin-block: 0 6px;
  margin-inline: 0;
}

.subtitle {
  margin: 0;
  color: var(--muted);
  font-size: 14px;
}

@media (prefers-color-scheme: light) {
  .hero-inner {
    border-color: #cbd5e1;
    background: linear-gradient(
      180deg,
      rgba(255, 255, 255, 65%),
      rgba(255, 255, 255, 25%)
    );
    box-shadow: 0 6px 20px rgba(12, 9, 35, 20%);
  }

  .title {
    margin-block-end: 10px;
    padding-block-end: 8px;
  }

  .subtitle {
    display: inline-block;
    border-radius: 10px;
    background: #f8fafc;
    padding-block: 6px;
    padding-inline: 10px;
  }
}

.content-wrap {
  display: grid;
  gap: 18px;
  grid-template-columns: 1fr;
  margin-block: 18px 48px;
  margin-inline: auto;
  max-inline-size: 1100px;
  padding-inline: 16px;
}

@media (min-width: 1000px) {
  .content-wrap {
    gap: 22px;
    grid-template-columns: 260px 1fr;
  }
}

.toc {
  position: sticky;
  display: none;
  block-size: fit-content;
  inset-block-start: 18px;
}

@media (min-width: 1000px) {
  .toc {
    display: block;
  }
}

.toc-card {
  padding: 14px;
  border: 1px solid var(--ring);
  border-radius: 14px;
  background: var(--card);
  box-shadow: var(--shadow);
}

.toc-head {
  color: var(--muted);
  font-size: 13px;
  font-weight: 600;
  letter-spacing: 0.3px;
  margin-block-end: 6px;
  text-transform: uppercase;
}

.toc nav ol {
  padding: 0;
  margin: 0;
  list-style: none;
}

.toc nav > ol > li {
  margin-block: 6px;
  margin-inline: 0;
}

.toc ol ol {
  margin-block: 8px;
  margin-inline: 16px 0;
}

.toc li {
  padding: 0;
  border: 0;
  border-radius: 0;
}

.toc li > a {
  display: block;
  border: 2px solid transparent;
  border-radius: 10px;
  color: var(--text);
  font-size: 16px;
  letter-spacing: 0.2px;
  padding-block: 10px;
  padding-inline: 12px;
  text-decoration: none;
  transition: color 0.2s ease, background-color 0.25s ease,
    border-color 0.25s ease, box-shadow 0.25s ease;
}

.toc li > a:hover {
  color: var(--accent);
}

.toc li.active > a {
  border-color: var(--accent);
  background: var(--accent-soft);
}

@media (prefers-color-scheme: light) {
  .toc li.active > a {
    background: linear-gradient(
      180deg,
      rgba(37, 99, 235, 8%),
      rgba(37, 99, 235, 4%)
    );
    box-shadow: inset 0 1px 0 rgba(255, 255, 255, 90%),
      0 1px 0 rgba(2, 6, 23, 4%);
  }
}

@media (prefers-color-scheme: dark) {
  .toc li.active > a {
    background: rgba(96, 165, 250, 12%);
    box-shadow: 0 0 0 1px rgba(96, 165, 250, 28%),
      inset 0 0 18px rgba(96, 165, 250, 10%);
  }
}

.card {
  padding: clamp(18px, 3vw, 28px);
  border: 1px solid var(--ring);
  border-radius: 18px;
  background: var(--card);
  box-shadow: var(--shadow);
}

.prose {
  color: var(--text);
  font-size: 17px;
  letter-spacing: 0.1px;
  line-height: 1.75;
  max-inline-size: 75ch;
}

.prose h2 {
  border-inline-start: 4px solid var(--accent);
  font-size: clamp(20px, 2.1vw, 24px);
  line-height: 1.35;
  margin-block: 28px 8px;
  margin-inline: 0;
  padding-inline-start: 10px;
}

.prose h3 {
  font-size: clamp(18px, 1.7vw, 20px);
  margin-block: 22px 6px;
  margin-inline: 0;
}

.prose h4 {
  font-size: 16px;
  font-weight: 600;
  margin-block: 16px 4px;
  margin-inline: 0;
}

.prose p,
.prose li {
  hyphens: auto;
  margin-block: 10px;
  margin-inline: 0;
  overflow-wrap: anywhere;
  text-align: justify;
  text-justify: inter-word;
}

.prose ul,
.prose ol {
  margin-block: 10px 16px;
  margin-inline: 22px 0;
}

.prose a {
  color: var(--accent);
  text-decoration: underline;
  text-underline-offset: 3px;
}

.prose a:hover {
  opacity: 0.9;
}

.doc-footer {
  border-block-start: 1px solid var(--ring);
  color: var(--muted);
  font-size: 14px;
  margin-block-start: 28px;
  padding-block-start: 16px;
}

:target {
  scroll-margin-top: 90px;
}

html {
  scroll-behavior: smooth;
}

@media (prefers-reduced-motion: reduce) {
  html {
    scroll-behavior: auto;
  }
}

@media print {
  .page {
    background: #fff !important;
  }

  .hero-inner,
  .card,
  .toc-card {
    box-shadow: none !important;
  }

  .toc {
    display: none !important;
  }
}
</style>
